### PR TITLE
add toplevel changelog

### LINKED ISSUE #5874: Missing Doc Required by OSC Governance
Please add CHANGELOG.md

 If Changelog already exists elsewhere, please add to main page of code and link accordingly. 

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

### PR DESCRIPTION
**Pull request by aleeusgr**
# Description

Add your description here, if it fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

closes #5874 

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

### CODE REVIEW

**Review by carbolymer — APPROVED** [review]
LGTM, Thanks!

**Comment by carbolymer** [comment]
@aleeusgr Can you sign your commits please? That's our requirement for all changes in the node. https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Comment by aleeusgr** [comment]
@carbolymer hello!

I am confused a bit by the guide, I did the following:
`git commit --amend --signoff`
` git push origin add-toplevel-changelog -f`

now the commit message contains my name and email, does it mean its signed?

Thank you!

**Comment by erikd** [comment]
> now the commit message contains my name and email, does it mean its signed

`git log --format=raw` show the log in the raw format which includes a crypto signing block.

**Comment by aleeusgr** [comment]
looks legit!

**Comment by carbolymer** [comment]
@aleeusgr I think you just need to upload your public key to github 
image

**Comment by aleeusgr** [comment]
@carbolymer thanks! 

Added GPG key to my GitHub account.

**Pull request merged**
